In [2]:
import pandas as pd

In [99]:
# 전체 곡 품사판별한 csv 파일 불러오기
song = pd.read_csv('song_okt_df.csv')

In [4]:
# 여자아이돌 곡 품사판별한 csv 파일 불러오기
female = pd.read_csv('female_okt_df.csv')

In [5]:
# 남자아이돌 곡 품사판별한 csv 파일 불러오기
male = pd.read_csv('male_okt_df.csv')

In [6]:
# 중복값을 지우고 유니크한 값만 보는 df.
# (중복값 지우지 않은 df도 살려놓는 것이 좋을 듯)
song_unique = song.drop_duplicates(subset='word')
female_unique = female.drop_duplicates(subset='word')
male_unique = male.drop_duplicates(subset='word')

In [7]:
song_unique.shape

(30588, 3)

In [8]:
song.head()

  word parts_of_speech  count
0   기다            Verb   1047
1    너            Noun  49848
2    와            Josa   6979
3    이            Noun  54797
4    밤            Noun   4929

In [ ]:
medals = df.pivot_table('word', ['word', 'Country'], 'parts_of_speech')

In [43]:
female_unique.pivot(index='word', columns='parts_of_speech')['count']

parts_of_speech,7/Number,Adjective,Adverb,Alpha,Conjunction,Eomi,Exclamation,Foreign,Josa,KoreanParticle,Modifier,Noun,Number,PreEomi,Punctuation,Suffix,Verb,VerbPrefix
word,,,,,,,,,,,,,,,,,,
NaN,NaN,NaN,NaN,76.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,340.0,NaN,NaN,NaN
!!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN
"!!,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
!),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.0,NaN,NaN,NaN
"!),",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN
"!,",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN
"""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN
""".",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN
$,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
$$,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.0,NaN,NaN,NaN
&,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,220.0,NaN,NaN,NaN
',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7873.0,NaN,NaN,NaN
'',NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN
'),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN
"',",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN
(,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,652.0,NaN,NaN,NaN
(*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,600.0,NaN,NaN,NaN
)!,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
"),",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN
).,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN
*,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.0,NaN,NaN,NaN
*(,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN
**,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN
***,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN
+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.0,NaN,NaN,NaN
",",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3818.0,NaN,NaN,NaN
",(",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN
-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,919.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
힐거,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
힐끔,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN
힐끔거리다,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
힐끔힐끔,NaN,NaN,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
힐끗,NaN,NaN,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
힐끗대다,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
힐끗힐끗,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
힘,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,373.0,NaN,NaN,NaN,NaN,NaN,NaN
힘겹다,NaN,50.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
힘껏,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,51.0,NaN,NaN,NaN,NaN,NaN,NaN
힘나다,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
힘내다,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,30.0,NaN
힘드다,NaN,128.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
힘들다,NaN,523.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
힘쌘,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,NaN,NaN,NaN
힘없다,NaN,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
힘좀,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
힘주다,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
힘줄,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
힘차다,NaN,12.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
힙,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
힙업,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
힙합,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN
힝,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
；,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
？,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
？？,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
？？？,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
�,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
�瑩嗤�,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
female_unique['gender'] = 'female'

/Users/yunkim/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [18]:
male_unique['gender'] = 'male'

/Users/yunkim/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.

In [47]:
male_unique.head()

   word parts_of_speech  count gender
0    그녀            Noun   1651   male
1     가            Josa  22055   male
2  떠나가다            Verb    951   male
3    있다       Adjective  16312   male
5    마저            Josa    337   male

In [76]:
fm_concat = pd.concat([female_unique_V, male_unique_V], axis=1, sort=False)
fm_concat.head()

    word parts_of_speech   count  gender  word parts_of_speech   count gender
0     기다            Verb   283.0  female   NaN             NaN     NaN    NaN
2    NaN             NaN     NaN     NaN  떠나가다            Verb   951.0   male
11  기다리다            Verb  1474.0  female   NaN             NaN     NaN    NaN
14   NaN             NaN     NaN     NaN   끝나다            Verb   749.0   male
18   NaN             NaN     NaN     NaN    이다            Verb  1836.0   male

In [49]:
fm_merge = pd.merge(female_unique_V, male_unique_V, on='word', how='outer')
fm_merge.shape

(1385, 7)

In [63]:
fm_merge = pd.merge(female_unique, male_unique, on=['word','parts_of_speech'], how='outer')
fm_merge.shape

(30224, 6)

In [64]:
# count_x, y를 female, male로 바꿔준 후 젠더 칼럼을 드롭해준다.
fm_merge = fm_merge.rename(index=str, columns={"count_x": "female", "count_y": "male"})
fm_merge = fm_merge.drop(['gender_x', 'gender_y'], axis=1)

In [65]:
fm_merge.head()

  word parts_of_speech   female     male
0   기다            Verb    283.0    678.0
1    너            Noun  16244.0  32123.0
2    와            Josa   2282.0   4415.0
3    이            Noun  17711.0      NaN
4    밤            Noun   1747.0   2983.0

In [10]:
song['parts_of_speech'].unique()

array(['Verb', 'Noun', 'Josa', 'Adverb', 'Alpha', 'Adjective', 'Eomi',
       'Punctuation', 'Determiner', 'Suffix', 'Modifier', 'VerbPrefix',
       'Number', 'Exclamation', 'Conjunction', 'Foreign', '/Punctuation',
       '7/Number', 'KoreanParticle', 'PreEomi', 'Hashtag', '50/Number'],
      dtype=object)

In [79]:
# 유니크한 값만 count로 sort해서 보기(품사별로)
fm_merge_V = fm_merge[fm_merge['parts_of_speech'] == 'Verb'].sort_values(by=['female'], ascending = False)
fm_merge_A = fm_merge[fm_merge['parts_of_speech'] == 'Adverb'].sort_values(by=['female'], ascending = False)
fm_merge_Adj = fm_merge[fm_merge['parts_of_speech'] == 'Adjective'].sort_values(by=['female'], ascending = False)
fm_merge_Alpha = fm_merge[fm_merge['parts_of_speech'] == 'Alpha'].sort_values(by=['female'], ascending = False)
fm_merge_Eomi = fm_merge[fm_merge['parts_of_speech'] == 'Eomi'].sort_values(by=['female'], ascending = False)

In [69]:
fm_merge_V[fm_merge_V['male'].isnull()].sort_values(by=['female'], ascending = False).head(10)

        word parts_of_speech  female  male
13451   다려지다            Verb     6.0   NaN
7749     봄타다            Verb     4.0   NaN
3825    잘라먹다            Verb     4.0   NaN
5565    넘겨보다            Verb     3.0   NaN
2251    잡혀가다            Verb     3.0   NaN
15095  엉클어지다            Verb     3.0   NaN
13477    써리다            Verb     3.0   NaN
14043  허우적이다            Verb     3.0   NaN
3047   간질거리다            Verb     3.0   NaN
4971    남아돌다            Verb     3.0   NaN

In [78]:
fm_merge_V[fm_merge_V['word'] == '기다려지다']

Empty DataFrame
Columns: [word, parts_of_speech, female, male]
Index: []

In [70]:
fm_merge_V[fm_merge_V['female'].isnull()].sort_values(by=['male'], ascending = False).head(10)

       word parts_of_speech  female  male
23198    돕다            Verb     NaN  94.0
20142   치키다            Verb     NaN  38.0
19571  들이키다            Verb     NaN  31.0
18111   겁니다            Verb     NaN  28.0
17149   재우다            Verb     NaN  17.0
17170   더디다            Verb     NaN  17.0
20514    쑤다            Verb     NaN  15.0
20360  돋아나다            Verb     NaN  15.0
18100   병들다            Verb     NaN  15.0
20012  지껄이다            Verb     NaN  14.0

In [95]:
fm_merge_Adj[fm_merge_Adj['male'].isnull()].sort_values(by=['female'], ascending = False).head(20)

         word parts_of_speech  female  male
4705       부다       Adjective    18.0   NaN
6204     앙큼하다       Adjective    11.0   NaN
6076     꿀꿀하다       Adjective    11.0   NaN
5066     소란하다       Adjective     7.0   NaN
9563    억지스럽다       Adjective     6.0   NaN
10003    맥빠지다       Adjective     5.0   NaN
7081     말랑하다       Adjective     4.0   NaN
11373  솔직담백하다       Adjective     4.0   NaN
10176  달짝지근하다       Adjective     4.0   NaN
7128      화하다       Adjective     3.0   NaN
11046    맛깔나다       Adjective     3.0   NaN
13435    급격하다       Adjective     3.0   NaN
10703  알록달록하다       Adjective     3.0   NaN
12272    싱싱하다       Adjective     3.0   NaN
13012    얼얼하다       Adjective     3.0   NaN
10108    보드랍다       Adjective     3.0   NaN
14481    느닷없다       Adjective     3.0   NaN
12622    날렵하다       Adjective     2.0   NaN
13891   부탁드리다       Adjective     2.0   NaN
9100      힘나다       Adjective     2.0   NaN

In [97]:
fm_merge_Adj[fm_merge_Adj['female'].isnull()].sort_values(by=['male'], ascending = False).head(20)

        word parts_of_speech  female  male
17633   아리땁다       Adjective     NaN  51.0
18124    푸르다       Adjective     NaN  33.0
17260   어떠하다       Adjective     NaN  17.0
21677   타락하다       Adjective     NaN  16.0
20588   처참하다       Adjective     NaN  15.0
19754   거대하다       Adjective     NaN  14.0
20576   머나멀다       Adjective     NaN  13.0
22809   끼부리다       Adjective     NaN  13.0
26630    드높다       Adjective     NaN  12.0
17775   비열하다       Adjective     NaN  11.0
17810   불과하다       Adjective     NaN  11.0
20300   강인하다       Adjective     NaN  10.0
17776   정직하다       Adjective     NaN  10.0
16953   수수하다       Adjective     NaN   9.0
17827   안전하다       Adjective     NaN   9.0
17852   삭막하다       Adjective     NaN   9.0
25856   팍팍하다       Adjective     NaN   9.0
16527  불공평하다       Adjective     NaN   9.0
17189   고달프다       Adjective     NaN   8.0
21061   현명하다       Adjective     NaN   8.0

In [93]:
fm_merge_A[fm_merge_A['male'].isnull()].sort_values(by=['female'], ascending = False).head(20)

       word parts_of_speech  female  male
784      같이          Adverb   655.0   NaN
469      어쩔          Adverb   160.0   NaN
12954   빙그르          Adverb    65.0   NaN
4288     조아          Adverb    36.0   NaN
3115   찰랑찰랑          Adverb    20.0   NaN
14291    쩝쩝          Adverb    15.0   NaN
14292     쩝          Adverb    15.0   NaN
10107  보들보들          Adverb    11.0   NaN
15020  씰룩씰룩          Adverb    11.0   NaN
13480   요렇게          Adverb    10.0   NaN
6179    우당탕          Adverb     9.0   NaN
4020   그렁그렁          Adverb     8.0   NaN
4508   깜박깜박          Adverb     7.0   NaN
2227   살짝살짝          Adverb     7.0   NaN
6371   하늘하늘          Adverb     7.0   NaN
9619   콩당콩당          Adverb     7.0   NaN
6061   말랑말랑          Adverb     7.0   NaN
14877  나풀나풀          Adverb     6.0   NaN
13446    해롱          Adverb     6.0   NaN
10207   쪼로록          Adverb     6.0   NaN

In [94]:
fm_merge_A[fm_merge_A['female'].isnull()].sort_values(by=['male'], ascending = False).head(20)

       word parts_of_speech  female   male
16670     씩          Adverb     NaN  432.0
16731     첨          Adverb     NaN   98.0
19456     걍          Adverb     NaN   19.0
19114    확확          Adverb     NaN   17.0
18573  왜냐하면          Adverb     NaN    9.0
27772   우르릉          Adverb     NaN    9.0
17667  휘청휘청          Adverb     NaN    8.0
19884    당당          Adverb     NaN    8.0
20716   찌그덕          Adverb     NaN    8.0
30112  나긋나긋          Adverb     NaN    8.0
17236    꽉꽉          Adverb     NaN    8.0
20234     왁          Adverb     NaN    7.0
25384  건들건들          Adverb     NaN    7.0
23517  서로서로          Adverb     NaN    7.0
23981    저벅          Adverb     NaN    6.0
17536  오래간만          Adverb     NaN    6.0
20489    방방          Adverb     NaN    6.0
21783  해롱해롱          Adverb     NaN    6.0
19322    팍팍          Adverb     NaN    6.0
17240    이왕          Adverb     NaN    5.0

In [82]:
fm_merge_Eomi.head()

     word parts_of_speech  female    male
49     거야            Eomi  1538.0  2308.0
1221   거니            Eomi   240.0   251.0
410    텐데            Eomi    66.0   203.0
2756   나요            Eomi    64.0    31.0
7254   까봐            Eomi    17.0    11.0

In [86]:
fm_merge_Eomi[fm_merge_Eomi['male'].isnull()].sort_values(by=['female'], ascending = False).head(10)

      word parts_of_speech  female  male
12352   길래            Eomi     2.0   NaN
1961    께요            Eomi     1.0   NaN
11202  옵니다            Eomi     1.0   NaN
11611   아요            Eomi     1.0   NaN
12732   였음            Eomi     1.0   NaN
16012  하오니            Eomi     1.0   NaN
16256    러            Eomi     1.0   NaN

In [85]:
fm_merge_Eomi[fm_merge_Eomi['female'].isnull()].sort_values(by=['male'], ascending = False).head(10)

      word parts_of_speech  female   male
16452    어            Eomi     NaN  569.0
17252   고만            Eomi     NaN   11.0
17108   여도            Eomi     NaN    6.0
17423   하듯            Eomi     NaN    5.0
25015   기로            Eomi     NaN    4.0
29612   어야            Eomi     NaN    3.0
23362   져서            Eomi     NaN    3.0
26119   하오            Eomi     NaN    2.0
27785  라고도            Eomi     NaN    1.0
29856   냐고            Eomi     NaN    1.0

In [89]:
fm_merge_Alpha[fm_merge_Alpha['male'].isnull()].sort_values(by=['female'], ascending = False).head(20)

         word parts_of_speech  female  male
1710       Ra           Alpha   164.0   NaN
14492   Rally           Alpha   114.0   NaN
1294      ddu           Alpha   109.0   NaN
3932      LIE           Alpha   105.0   NaN
13699     pam           Alpha    96.0   NaN
9543      YAH           Alpha    94.0   NaN
1709   Shuppy           Alpha    90.0   NaN
2214      NaN           Alpha    76.0   NaN
11460    goma           Alpha    71.0   NaN
10334    Echo           Alpha    66.0   NaN
2494     Bell           Alpha    63.0   NaN
6957   mister           Alpha    59.0   NaN
2158     EASY           Alpha    56.0   NaN
11001    OooP           Alpha    56.0   NaN
12749   jelly           Alpha    54.0   NaN
15751      Al           Alpha    54.0   NaN
9590   whatta           Alpha    54.0   NaN
6481     Peek           Alpha    52.0   NaN
10679  Holler           Alpha    52.0   NaN
11000    DORI           Alpha    48.0   NaN

In [90]:
fm_merge_Alpha[fm_merge_Alpha['female'].isnull()].sort_values(by=['male'], ascending = False).head(20)

            word parts_of_speech  female  male
23989         Ru           Alpha     NaN  75.0
23616        Dee           Alpha     NaN  72.0
20430       tear           Alpha     NaN  58.0
26455       Wolf           Alpha     NaN  57.0
22864     SHINee           Alpha     NaN  55.0
21180       Deal           Alpha     NaN  53.0
28031     hurray           Alpha     NaN  50.0
23427     Walker           Alpha     NaN  49.0
17641        YEH           Alpha     NaN  49.0
24803      Getup           Alpha     NaN  45.0
23730     BOUNCE           Alpha     NaN  44.0
22924         Jo           Alpha     NaN  44.0
28057  obsession           Alpha     NaN  43.0
18963       YOLO           Alpha     NaN  43.0
18635     Cowboy           Alpha     NaN  42.0
18973      giddy           Alpha     NaN  41.0
20948       Joke           Alpha     NaN  40.0
19312      lemme           Alpha     NaN  40.0
25826      Vroom           Alpha     NaN  40.0
25422      BLING           Alpha     NaN  40.0

In [ ]:
#if you want to specify the order of the column, you can use insert
#here, we are inserting at index 1 (so should be second col in dataframe)
df.insert(1, 'My 2nd new column', 'default value 2')
df

In [ ]:
# 유니크한 값만 count로 sort해서 보기(품사별로)
female_unique_N = female_unique[female_unique['parts_of_speech'] == 'Adverb'].sort_values(by=['count'], ascending = False)
female_unique_N.head()

In [ ]:
Adverb = song_okt_df_drop[song_okt_df_drop['parts_of_speech'] == 'Adverb']
# Verb['word'].str.len()

In [ ]:
# 일정 길이 이상 단어만 보기
two_A = (Adverb['word'].str.len() >= 2)
three_A = (Adverb['word'].str.len() >= 3)
two_Adverb = Adverb.loc[two_A]
three_Adverb = Adverb.loc[three_A]